services:
  # postgres database
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 2s
      retries: 20
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    networks:
      - server-network
  application:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: application
    env_file:
      - .env.dev
    ports:
      - '${APPLICATION_PORT}:${APPLICATION_PORT}'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - server-network

networks:
  server-network:
    name: server-network

volumes:
  postgres_data: